from __future__ import annotations


DEFAULT_ROLES: tuple[dict[str, str], ...] = (
    {"slug": "admin", "name": "Admin", "description": "Legacy admin role"},
    {"slug": "manager", "name": "Manager", "description": "Legacy manager role"},
    {"slug": "hr", "name": "HR", "description": "Legacy HR role"},
    {"slug": "staff", "name": "Staff", "description": "Legacy staff/member role"},
    {"slug": "ADMIN", "name": "Admin", "description": "Quan tri toan he thong"},
    {"slug": "MANAGER", "name": "Manager", "description": "Quan ly du an, team, task va KPI cua bo phan"},
    {"slug": "LEADER", "name": "Leader", "description": "Quan ly task cua nhom nho"},
    {"slug": "MEMBER", "name": "Member", "description": "Cap nhat task va xem KPI ca nhan"},
    {"slug": "HR", "name": "HR", "description": "Quan ly nhan vien va phong ban"},
    {"slug": "AUDITOR", "name": "Auditor", "description": "Xem audit log va bao cao van hanh"},
)


DEFAULT_PERMISSIONS: tuple[dict[str, str], ...] = (
    {"key": "users.create", "name": "Create users", "category": "users"},
    {"key": "users.view", "name": "View users", "category": "users"},
    {"key": "roles.view", "name": "View roles and permissions", "category": "rbac"},
    {"key": "roles.manage", "name": "Manage role permissions", "category": "rbac"},
    {"key": "tasks.create", "name": "Create tasks", "category": "tasks"},
    {"key": "tasks.update_any", "name": "Update any task", "category": "tasks"},
    {"key": "tasks.update_own", "name": "Update own task", "category": "tasks"},
    {"key": "projects.manage", "name": "Manage projects", "category": "projects"},
    {"key": "projects.view", "name": "View accessible projects", "category": "projects"},
    {"key": "sprints.manage", "name": "Manage sprints", "category": "sprints"},
    {"key": "sprints.view", "name": "View sprints", "category": "sprints"},
    {"key": "kpi.view", "name": "View KPI", "category": "kpi"},
    {"key": "kpi.adjust", "name": "Adjust KPI", "category": "kpi"},
    {"key": "reports.export", "name": "Export reports", "category": "reports"},
    {"key": "ai.preview", "name": "Preview AI task breakdown", "category": "ai"},
    {"key": "ai.import", "name": "Import AI tasks", "category": "ai"},
    {"key": "rag.manage", "name": "Manage RAG documents", "category": "rag"},
    {"key": "rag.query", "name": "Query RAG context", "category": "rag"},
    {"key": "teams.view", "name": "View Teams integration", "category": "teams"},
    {"key": "teams.manage", "name": "Manage Teams queue and reminders", "category": "teams"},
    {"key": "monitoring.view", "name": "View monitoring", "category": "monitoring"},
    {"key": "monitoring.admin", "name": "Admin monitoring actions", "category": "monitoring"},
    {"key": "DASHBOARD_VIEW", "name": "View dashboard", "category": "dashboard"},
    {"key": "KANBAN_VIEW", "name": "View kanban", "category": "kanban"},
    {"key": "KANBAN_MANAGE_ALL", "name": "Manage all kanban tasks", "category": "kanban"},
    {"key": "KANBAN_MANAGE_TEAM", "name": "Manage team kanban tasks", "category": "kanban"},
    {"key": "KANBAN_UPDATE_OWN_TASK", "name": "Update own task", "category": "kanban"},
    {"key": "PROJECT_VIEW", "name": "View projects", "category": "projects"},
    {"key": "PROJECT_CREATE", "name": "Create projects", "category": "projects"},
    {"key": "PROJECT_UPDATE", "name": "Update projects", "category": "projects"},
    {"key": "PROJECT_DELETE", "name": "Delete projects", "category": "projects"},
    {"key": "PROJECT_MANAGE_MEMBERS", "name": "Manage project members", "category": "projects"},
    {"key": "KPI_VIEW_OWN", "name": "View own KPI", "category": "kpi"},
    {"key": "KPI_VIEW_TEAM", "name": "View team KPI", "category": "kpi"},
    {"key": "KPI_VIEW_ALL", "name": "View all KPI", "category": "kpi"},
    {"key": "KPI_MANAGE", "name": "Manage KPI", "category": "kpi"},
    {"key": "REPORT_VIEW_TEAM", "name": "View team reports", "category": "reports"},
    {"key": "REPORT_VIEW_ALL", "name": "View all reports", "category": "reports"},
    {"key": "REPORT_EXPORT", "name": "Export reports", "category": "reports"},
    {"key": "AI_TASK_VIEW", "name": "View AI tasks", "category": "ai"},
    {"key": "AI_TASK_GENERATE", "name": "Generate AI tasks", "category": "ai"},
    {"key": "AI_TASK_REVIEW", "name": "Review AI tasks", "category": "ai"},
    {"key": "AI_TASK_IMPORT", "name": "Import AI tasks", "category": "ai"},
    {"key": "TEAM_VIEW", "name": "View teams", "category": "teams"},
    {"key": "TEAM_MANAGE", "name": "Manage teams", "category": "teams"},
    {"key": "USER_VIEW", "name": "View users", "category": "users"},
    {"key": "USER_CREATE", "name": "Create users", "category": "users"},
    {"key": "USER_UPDATE", "name": "Update users", "category": "users"},
    {"key": "USER_DEACTIVATE", "name": "Deactivate users", "category": "users"},
    {"key": "USER_RESET_PASSWORD", "name": "Reset user passwords", "category": "users"},
    {"key": "ROLE_VIEW", "name": "View roles", "category": "rbac"},
    {"key": "ROLE_MANAGE", "name": "Manage roles", "category": "rbac"},
    {"key": "DEPARTMENT_VIEW", "name": "View departments", "category": "departments"},
    {"key": "DEPARTMENT_MANAGE", "name": "Manage departments", "category": "departments"},
    {"key": "AUDIT_VIEW", "name": "View audit log", "category": "audit"},
    {"key": "OPS_VIEW", "name": "View operations", "category": "monitoring"},
)


ADMIN_PERMISSIONS = tuple(item["key"] for item in DEFAULT_PERMISSIONS)

DEFAULT_ROLE_PERMISSION_KEYS: dict[str, tuple[str, ...]] = {
    "admin": ADMIN_PERMISSIONS,
    "manager": (
        "users.view",
        "projects.manage",
        "projects.view",
        "tasks.create",
        "tasks.update_any",
        "tasks.update_own",
        "sprints.manage",
        "sprints.view",
        "kpi.view",
        "reports.export",
        "ai.preview",
        "ai.import",
        "rag.manage",
        "rag.query",
        "teams.view",
        "teams.manage",
        "monitoring.view",
    ),
    "hr": (
        "users.view",
        "projects.view",
        "sprints.view",
        "kpi.view",
        "kpi.adjust",
        "reports.export",
        "teams.view",
        "teams.manage",
        "monitoring.view",
    ),
    "staff": (
        "projects.view",
        "tasks.update_own",
        "sprints.view",
        "kpi.view",
        "teams.view",
    ),
    "ADMIN": tuple(item["key"] for item in DEFAULT_PERMISSIONS),
    "MANAGER": (
        "DASHBOARD_VIEW", "KANBAN_VIEW", "KANBAN_MANAGE_TEAM", "KANBAN_UPDATE_OWN_TASK",
        "PROJECT_VIEW", "PROJECT_CREATE", "PROJECT_UPDATE", "PROJECT_MANAGE_MEMBERS",
        "KPI_VIEW_OWN", "KPI_VIEW_TEAM", "KPI_MANAGE",
        "REPORT_VIEW_TEAM", "REPORT_EXPORT",
        "AI_TASK_VIEW", "AI_TASK_GENERATE", "AI_TASK_REVIEW", "AI_TASK_IMPORT",
        "TEAM_VIEW", "TEAM_MANAGE",
        "users.view", "projects.manage", "projects.view", "tasks.create", "tasks.update_any",
        "tasks.update_own", "sprints.manage", "sprints.view", "kpi.view", "kpi.adjust",
        "reports.export", "ai.preview", "ai.import", "rag.manage", "rag.query",
        "teams.view", "teams.manage", "monitoring.view",
    ),
    "LEADER": (
        "DASHBOARD_VIEW", "KANBAN_VIEW", "KANBAN_MANAGE_TEAM", "KANBAN_UPDATE_OWN_TASK",
        "PROJECT_VIEW", "KPI_VIEW_OWN", "KPI_VIEW_TEAM", "REPORT_VIEW_TEAM",
        "AI_TASK_VIEW", "TEAM_VIEW",
        "projects.view", "tasks.create", "tasks.update_any", "tasks.update_own",
        "sprints.view", "kpi.view", "ai.preview", "rag.query", "teams.view",
    ),
    "MEMBER": (
        "DASHBOARD_VIEW", "KANBAN_VIEW", "KANBAN_UPDATE_OWN_TASK", "PROJECT_VIEW",
        "KPI_VIEW_OWN", "AI_TASK_VIEW", "TEAM_VIEW",
        "projects.view", "tasks.update_own", "sprints.view", "kpi.view", "teams.view",
    ),
    "HR": (
        "DASHBOARD_VIEW", "PROJECT_VIEW", "KPI_VIEW_TEAM", "KPI_VIEW_ALL",
        "REPORT_VIEW_TEAM", "REPORT_VIEW_ALL", "REPORT_EXPORT", "TEAM_VIEW", "TEAM_MANAGE",
        "USER_VIEW", "USER_CREATE", "USER_UPDATE", "USER_DEACTIVATE", "USER_RESET_PASSWORD",
        "DEPARTMENT_VIEW", "DEPARTMENT_MANAGE", "OPS_VIEW",
        "users.view", "users.create", "projects.view", "sprints.view", "kpi.view",
        "kpi.adjust", "reports.export", "teams.view", "teams.manage", "monitoring.view",
    ),
    "AUDITOR": (
        "DASHBOARD_VIEW", "REPORT_VIEW_ALL", "REPORT_EXPORT", "AUDIT_VIEW", "OPS_VIEW",
        "reports.export", "monitoring.view",
    ),
}
